import { Bell, CalendarDays, FileDown, Plus } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { addAppointment, confirmAppointment, createShift, deleteAppointment, getIsotopeSettings, getScanners, getSession, getSetupStatus, getShift, logout, reportUrl, updateAppointment, updateSourceActivity, type ApiAppointment, type ApiShift, type Session } from './api'
import { initialPlans, isotopeConfig, scanners as demoScanners } from './data'
import { ActivityPanel } from './components/ActivityPanel'
import { AdminPage } from './components/AdminPage'
import { HistoryPage } from './components/HistoryPage'
import { LoginPage } from './components/LoginPage'
import { NewPatientDialog } from './components/NewPatientDialog'
import { PatientTable } from './components/PatientTable'
import { Planner } from './components/Planner'
import { Sidebar, type AppView } from './components/Sidebar'
import { SetupPage } from './components/SetupPage'
import type { Isotope, PatientPlan, Scanner } from './types'

const isotopes: Isotope[] = ['F-18', 'Ga-68']
const today = () => new Intl.DateTimeFormat('en-CA').format(new Date())
function appointmentToPlan(item: ApiAppointment): PatientPlan { const date = new Date(item.injectionAt); return { id: item.id, number: item.patientNumber, weight: item.weightKg, isotope: item.isotopeCode, protocol: item.protocolName, scannerId: item.scannerId, startMinutes: date.getHours() * 60 + date.getMinutes(), duration: item.durationMinutes, confirmed: item.confirmed } }

function Dashboard({ session, demo, onLogout }: { session: Session; demo: boolean; onLogout: () => void }) {
  const [scanners, setScanners] = useState<Scanner[]>(demo ? demoScanners : []), [plans, setPlans] = useState<PatientPlan[]>(demo ? initialPlans : []), [shifts, setShifts] = useState<Partial<Record<Isotope, ApiShift | null>>>({})
  const [date, setDate] = useState(today), [isotope, setIsotope] = useState<Isotope>('F-18'), [activity, setActivity] = useState(37000), [dialog, setDialog] = useState(false), [editing, setEditing] = useState<PatientPlan>(), [notice, setNotice] = useState<string>(), [view, setView] = useState<AppView>('plan')
  const activeShift = shifts[isotope]
  useEffect(() => { if (demo) return; void Promise.all([getScanners(), getIsotopeSettings(), ...isotopes.map((x) => getShift(date, x))]).then(([scannerRows, settings, f18, ga68]) => { settings.forEach((x) => { isotopeConfig[x.isotopeCode].halfLife = x.halfLifeMinutes; isotopeConfig[x.isotopeCode].coefficient = x.doseCoefficientMbqPerKg }); setScanners(scannerRows); setShifts({ 'F-18': f18, 'Ga-68': ga68 }); setPlans([...(f18?.appointments ?? []), ...(ga68?.appointments ?? [])].map(appointmentToPlan)); setActivity(f18?.sourceActivityMbq ?? settings.find((x) => x.isotopeCode === 'F-18')?.defaultSourceActivityMbq ?? 37000) }).catch((e: unknown) => setNotice(e instanceof Error ? e.message : 'Не удалось загрузить смену.')) }, [date, demo])
  useEffect(() => setActivity(activeShift?.sourceActivityMbq ?? 37000), [activeShift, isotope])
  async function addPlan(plan: PatientPlan) { if (demo) { setPlans((x) => [...x, plan]); return }; const hours = String(Math.floor(plan.startMinutes / 60)).padStart(2, '0'), minutes = String(plan.startMinutes % 60).padStart(2, '0'); const draft = { scannerId: plan.scannerId, patientNumber: plan.number, weightKg: plan.weight, protocolName: plan.protocol, injectionAt: new Date(`${date}T${hours}:${minutes}:00`).toISOString(), durationMinutes: plan.duration }; if (activeShift) { const created = await addAppointment(activeShift.id, draft); setPlans((x) => [...x, appointmentToPlan(created)]); setShifts((x) => ({ ...x, [isotope]: { ...activeShift, appointments: [...activeShift.appointments, created] } })); return }; const shift = await createShift(date, isotope, activity, draft); setShifts((x) => ({ ...x, [isotope]: shift })); setPlans((x) => [...x, ...shift.appointments.map(appointmentToPlan)]) }
  async function savePlan(plan: PatientPlan) { if (!editing) return addPlan(plan); if (demo) { setPlans((items) => items.map((item) => item.id === plan.id ? plan : item)); return }; const hours = String(Math.floor(plan.startMinutes / 60)).padStart(2, '0'), minutes = String(plan.startMinutes % 60).padStart(2, '0'); const saved = await updateAppointment(plan.id, { scannerId: plan.scannerId, patientNumber: plan.number, weightKg: plan.weight, protocolName: plan.protocol, injectionAt: new Date(`${date}T${hours}:${minutes}:00`).toISOString(), durationMinutes: plan.duration }); setPlans((items) => items.map((item) => item.id === plan.id ? appointmentToPlan(saved) : item)); setEditing(undefined) }
  async function removePlan(plan: PatientPlan) { if (!demo) await deleteAppointment(plan.id); setPlans((items) => items.filter((item) => item.id !== plan.id)); setShifts((items) => ({ ...items, [plan.isotope]: items[plan.isotope] ? { ...items[plan.isotope]!, appointments: items[plan.isotope]!.appointments.filter((item) => item.id !== plan.id) } : null })) }
  async function saveActivity() { if (!activeShift || demo) return; try { await updateSourceActivity(activeShift.id, activity); setShifts((x) => ({ ...x, [isotope]: { ...activeShift, sourceActivityMbq: activity } })) } catch (e) { setNotice(e instanceof Error ? e.message : 'Не удалось сохранить активность.') } }
  async function confirm(id: string) { try { if (!demo) await confirmAppointment(id); setPlans((x) => x.map((p) => p.id === id ? { ...p, confirmed: true } : p)) } catch (e) { setNotice(e instanceof Error ? e.message : 'Не удалось подтвердить запись.') } }
  const selectedPlans = useMemo(() => plans.filter((x) => x.isotope === isotope), [plans, isotope])
  const page = view === 'settings' ? <AdminPage /> : view === 'history' ? <HistoryPage onSelect={(nextDate) => { setDate(nextDate); setView('plan') }} /> : <><header className="topbar"><div><h1>План смены</h1><label className="date-selector"><CalendarDays size={18} /><input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></label></div><div className="topbar-actions"><button className="icon-button" type="button" aria-label="Уведомления"><Bell size={20} /></button><button className="button button--secondary" disabled={!activeShift} onClick={() => activeShift && window.open(reportUrl(activeShift.id), '_blank', 'noopener')}><FileDown size={19} /> PDF</button><button className="button" disabled={!demo && !scanners.length} onClick={() => { setEditing(undefined); setDialog(true) }}><Plus size={19} /> Добавить пациента</button></div></header>{notice && <p className="dashboard-notice">{notice}</p>}<div className="dashboard-grid"><Planner scanners={scanners} plans={plans} /><ActivityPanel isotope={isotope} sourceActivity={activity} plans={selectedPlans} onIsotopeChange={setIsotope} onSourceActivityChange={setActivity} onSaveSourceActivity={saveActivity} savingActivity={false} isSaved={Boolean(activeShift)} /></div><PatientTable plans={plans} canConfirm onConfirm={confirm} onEdit={(plan) => { setEditing(plan); setIsotope(plan.isotope); setDialog(true) }} onDelete={removePlan} /></>
  return <div className="app-shell"><Sidebar email={session.email} onLogout={onLogout} view={view} onNavigate={setView} /><main className="main-content">{page}</main>{dialog && <NewPatientDialog scanners={scanners} isotope={isotope} initialPlan={editing} onClose={() => { setDialog(false); setEditing(undefined) }} onSave={savePlan} />}</div>
}

export default function App() { const [session, setSession] = useState<Session | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState<string>(), [needsSetup, setNeedsSetup] = useState(false); const demo = new URLSearchParams(window.location.search).has('demo'); useEffect(() => { if (demo) { setSession({ email: 'demo@radioplan.local', role: 'operator' }); setLoading(false); return }; void getSession().then(async (current) => { setSession(current); if (!current) setNeedsSetup((await getSetupStatus()).needsSetup) }).catch((e: unknown) => setError(e instanceof Error ? e.message : 'Не удалось подключиться к серверу.')).finally(() => setLoading(false)) }, [demo]); if (loading) return <main className="loading-screen">Проверка защищённого сеанса…</main>; if (!session && needsSetup) return <SetupPage onConfigured={setSession} />; if (!session) return <LoginPage initialError={error} onLoggedIn={setSession} />; return <Dashboard session={session} demo={demo} onLogout={() => { void logout().finally(() => setSession(null)) }} /> }
