import { ChartLine, Info, Pencil, Save, TriangleAlert } from 'lucide-react'
import { useEffect, useState } from 'react'
import type { Isotope, PatientPlan } from '../types'

type Props = { isotope: Isotope; sourceActivity: number; measuredAt: string; halfLifeMinutes: number; coefficient: number; plans: PatientPlan[]; onIsotopeChange: (value: Isotope) => void; onSourceActivityChange: (value: number) => void; onMeasuredAtChange: (value: string) => void; onSaveSourceActivity: () => void; savingActivity: boolean; isSaved: boolean }
const startOfDay = 8 * 60
const formatDateTime = (value: string) => { const [date, time] = value.split('T'); const [year, month, day] = date.split('-'); return `${day}.${month}.${year} ${time}` }
function remainingAt(activity: number, halfLife: number, coefficient: number, plans: PatientPlan[], moment: number) {
  const ordered = plans.filter((plan) => plan.injectionMinutes <= moment).slice().sort((a, b) => a.injectionMinutes - b.injectionMinutes)
  let result = activity; let previous: number | undefined
  for (const plan of ordered) { if (previous !== undefined) result *= 2 ** (-(plan.injectionMinutes - previous) / halfLife); result -= plan.weight * coefficient; previous = plan.injectionMinutes }
  return Math.max(0, result * (previous === undefined ? 1 : 2 ** (-(moment - previous) / halfLife)))
}
export function doseFor(plan: PatientPlan) { return Math.round(plan.weight * plan.coefficient) }
export function ActivityPanel({ isotope, sourceActivity, measuredAt, halfLifeMinutes, coefficient, plans, onIsotopeChange, onSourceActivityChange, onMeasuredAtChange, onSaveSourceActivity, savingActivity, isSaved }: Props) {
  const [editing, setEditing] = useState(!isSaved)
  const [showChart, setShowChart] = useState(false)
  useEffect(() => { if (isSaved) setEditing(false) }, [isSaved])
  const current = Math.round(remainingAt(sourceActivity, halfLifeMinutes, coefficient, plans, 12 * 60 + 30)); const warning = current < sourceActivity * 0.25
  const points = Array.from({ length: 9 }, (_, index) => ({ x: index, activity: remainingAt(sourceActivity, halfLifeMinutes, coefficient, plans, startOfDay + index * 60) }))
  const max = Math.max(sourceActivity, 1); const path = points.map(({ x, activity }, index) => `${index === 0 ? 'M' : 'L'} ${x * 12.5} ${100 - (activity / max) * 88}`).join(' ')
  const area = `${path} L 100 100 L 0 100 Z`
  const plannedDose = Math.round(plans.reduce((total, plan) => total + doseFor(plan), 0)); const end = Math.round(points.at(-1)?.activity ?? sourceActivity)
  const chart = showChart && <section className="panel activity-chart-panel" aria-label="График остаточной активности"><div className="chart-header"><div><strong>Остаточная активность</strong><span>с учётом распада и введений</span></div><b>{current.toLocaleString('ru-RU')} <small>МБк</small></b></div><div className="chart"><svg viewBox="0 0 100 112" preserveAspectRatio="none" role="img"><defs><linearGradient id="activity-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#1263dc" stopOpacity=".24"/><stop offset="100%" stopColor="#1263dc" stopOpacity=".02"/></linearGradient></defs>{[16, 40, 64, 88].map((y) => <line key={y} x1="0" x2="100" y1={y} y2={y} />)}<path className="chart-area" d={area} /><path d={path} /></svg><div className="chart-axis"><span>08:00</span><span>10:00</span><span>12:00</span><span>14:00</span><span>16:00</span></div></div><div className="chart-summary"><span><b>08:00</b>{Math.round(points[0].activity).toLocaleString('ru-RU')} МБк</span><span><b>План введений</b>{plannedDose.toLocaleString('ru-RU')} МБк</span><span><b>16:00</b>{end.toLocaleString('ru-RU')} МБк</span></div></section>
  if (isSaved && !editing) return <>{<section className="shift-summary" aria-label="Параметры открытой смены"><span className="stage-number">1</span><strong>Смена</strong><span>{isotope}</span><span>{sourceActivity.toLocaleString('ru-RU')} МБк</span><span>{formatDateTime(measuredAt)}</span><span>Остаток {current.toLocaleString('ru-RU')} МБк</span><button className="icon-button" type="button" title={showChart ? 'Скрыть график активности' : 'Показать график активности'} aria-label={showChart ? 'Скрыть график активности' : 'Показать график активности'} onClick={() => setShowChart((value) => !value)}><ChartLine size={17} /></button><button className="icon-button" type="button" title="Изменить параметры смены" aria-label="Изменить параметры смены" onClick={() => setEditing(true)}><Pencil size={17} /></button></section>}{chart}</>
  return <><section className="panel activity-panel" aria-labelledby="activity-title"><div className="stage-heading"><span className="stage-number">1</span><div><h2 id="activity-title">Смена</h2><p>Исходные данные РФП</p></div></div><div className="activity-fields"><label>Изотоп<select aria-label="Изотоп" value={isotope} onChange={(event) => onIsotopeChange(event.target.value as Isotope)}><option>F-18</option><option>Ga-68</option></select></label><label>Активность, МБк<input aria-label="Фактическая активность при поставке" type="number" min="0" value={sourceActivity} onChange={(event) => onSourceActivityChange(Number(event.target.value))} /></label><label>Время замера<input type="datetime-local" value={measuredAt} onChange={(event) => onMeasuredAtChange(event.target.value)} /></label><div className="activity-result"><span>Остаток в 12:30</span><strong>{current.toLocaleString('ru-RU')} <small>МБк</small></strong></div>{isSaved && <button className="icon-button" type="button" title="Сохранить изменённую активность" aria-label="Сохранить изменённую активность" onClick={() => { onSaveSourceActivity(); setEditing(false) }} disabled={savingActivity}><Save size={18} /></button>}</div>{warning && <div className="alert"><TriangleAlert size={18} /><span><strong>Низкий остаток активности.</strong> Проверьте расписание пациентов.</span></div>}<button className="calculation-chart" type="button" title={showChart ? 'Скрыть график активности' : 'Показать график активности'} aria-label={showChart ? 'Скрыть график активности' : 'Показать график активности'} onClick={() => setShowChart((value) => !value)}><ChartLine size={16} /></button><button className="calculation-info" type="button" title={`Расчёт: период полураспада ${halfLifeMinutes} мин; коэффициент ${coefficient} МБк/кг.`} aria-label="Параметры расчёта"><Info size={16} /></button></section>{chart}</>
}
