import { useEffect, useState, type FormEvent } from 'react'
import { addProtocol, createUser, getIsotopeSettings, getProtocols, getUsers, updateIsotopeSettings, type IsotopeSettings, type Protocol, type User } from '../api'

export function AdminPage() {
  const [settings, setSettings] = useState<IsotopeSettings[]>([]); const [protocols, setProtocols] = useState<Protocol[]>([]); const [users, setUsers] = useState<User[]>([]); const [notice, setNotice] = useState<string>()
  useEffect(() => { void Promise.all([getIsotopeSettings(), getProtocols(), getUsers()]).then(([s,p,u]) => { setSettings(s); setProtocols(p); setUsers(u) }).catch((e: unknown) => setNotice(e instanceof Error ? e.message : 'Не удалось загрузить настройки.')) }, [])
  async function saveSetting(setting: IsotopeSettings) { try { await updateIsotopeSettings(setting.isotopeCode, setting); setNotice(`Настройки ${setting.isotopeCode} сохранены.`) } catch (e) { setNotice(e instanceof Error ? e.message : 'Ошибка сохранения.') } }
  async function addUser(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { const user = await createUser(String(data.get('email')), String(data.get('password')), String(data.get('role')) as User['role']); setUsers((items) => [...items, user]); event.currentTarget.reset(); setNotice('Пользователь создан.') } catch (e) { setNotice(e instanceof Error ? e.message : 'Ошибка создания пользователя.') } }
  async function createProtocol(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { const protocol = await addProtocol({ isotopeCode: String(data.get('isotopeCode')) as Protocol['isotopeCode'], name: String(data.get('name')), durationMinutes: Number(data.get('durationMinutes')), isActive: true }); setProtocols((items) => [...items, protocol]); event.currentTarget.reset(); setNotice('Протокол добавлен.') } catch (e) { setNotice(e instanceof Error ? e.message : 'Ошибка создания протокола.') } }
  return <section className="settings-page"><h1>Настройки</h1>{notice && <p className="dashboard-notice">{notice}</p>}<section className="panel settings-section"><h2>Параметры расчёта РФП</h2><p>Значения F‑18 перенесены из предоставленной расчётной таблицы.</p>{settings.map((setting) => <div className="settings-row" key={setting.isotopeCode}><strong>{setting.isotopeCode}</strong><label>Полураспад, мин<input type="number" value={setting.halfLifeMinutes} onChange={(e) => setSettings((items) => items.map((x) => x.isotopeCode === setting.isotopeCode ? { ...x, halfLifeMinutes: Number(e.target.value) } : x))} /></label><label>Коэф., МБк/кг<input type="number" step="0.001" value={setting.doseCoefficientMbqPerKg} onChange={(e) => setSettings((items) => items.map((x) => x.isotopeCode === setting.isotopeCode ? { ...x, doseCoefficientMbqPerKg: Number(e.target.value) } : x))} /></label><label>Старт, МБк<input type="number" value={setting.defaultSourceActivityMbq} onChange={(e) => setSettings((items) => items.map((x) => x.isotopeCode === setting.isotopeCode ? { ...x, defaultSourceActivityMbq: Number(e.target.value) } : x))} /></label><button className="button" type="button" onClick={() => void saveSetting(setting)}>Сохранить</button></div>)}</section><section className="panel settings-section"><h2>Протоколы</h2><div className="settings-list">{protocols.filter((x) => x.isActive).map((x) => <span key={x.id}>{x.isotopeCode} · {x.name} · {x.durationMinutes} мин</span>)}</div><form className="inline-form" onSubmit={createProtocol}><select name="isotopeCode"><option>F-18</option><option>Ga-68</option></select><input name="name" placeholder="Название протокола" required /><input name="durationMinutes" type="number" min="1" max="300" placeholder="Минуты" required /><button className="button">Добавить</button></form></section><section className="panel settings-section"><h2>Пользователи</h2><div className="settings-list">{users.map((x) => <span key={x.id}>{x.email} · {x.role === 'administrator' ? 'Администратор' : 'Оператор'}</span>)}</div><form className="inline-form" onSubmit={addUser}><input name="email" type="email" placeholder="email" required /><input name="password" type="password" minLength={12} placeholder="Пароль (от 12 символов)" required /><select name="role"><option value="operator">Оператор</option><option value="administrator">Администратор</option></select><button className="button">Создать</button></form></section></section>
}
